---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: simpledbs.example.com
spec:
  group: example.com
  names:
    kind: SimpleDB
    listKind: SimpleDBList
    plural: simpledbs
    singular: simpledb
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpledb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: simpledb
  template:
    metadata:
      labels:
        name: simpledb
    spec:
      serviceAccountName: simpledb
      containers:
        - name: simpledb
          image: hk1232/operator-simpledb-runner:0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "simpledb"
