apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-world
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      #serviceAccountName: hello-world
      containers:
        - name: hello-world
          # Replace this with the built image name
          image: hk1232/operator-hello-world:0.2
          imagePullPolicy: Always
          #env:
          #  - name: WATCH_NAMESPACE
          #    valueFrom:
          #      fieldRef:
          #        fieldPath: metadata.namespace
          #  - name: OPERATOR_NAME
          #    value: "hello-world"
