---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simpledb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: simpledb
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - "*"
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - example.com
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simpledb
subjects:
- kind: ServiceAccount
  name: simpledb
roleRef:
  kind: Role
  name: simpledb
  apiGroup: rbac.authorization.k8s.io
