kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hello-world
subjects:
- kind: ServiceAccount
  name: hello-world
roleRef:
  kind: Role
  name: hello-world
  apiGroup: rbac.authorization.k8s.io
