---
- set_fact:
    mysql_ip: "{{ lookup('dig',mysql_app_name) }}"

- include_tasks: mariadb_install.yml
  when: mysql_ip == "NXDOMAIN"

# TODO - curl version from app itself

- include_tasks: mariadb_upgrade.yml
  #when: 

