---
- template:
    src: update.sql.j2
    dest: /tmp/update.sql

- name: Simulate DDL Changes
  mysql_db:
    login_host: mariadb
    login_user: root
    login_password: mypassword
    name: mydatabase
    state: import
    target: /tmp/update.sql
