---
- template:
    src: update.sql.j2
    dest: /tmp/update.sql

- name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
  mysql_db:
    login_host: mariadb
    login_user: root
    login_password: mypassword
    name: mydatabase
    state: import
    target: /tmp/update.sql
